spring.application.name=candidat
server.port=8081

# H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.datasource.username=Badia
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:candidatdb
spring.jpa.hibernate.ddl-auto=create

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# Actuator - EXPOSER health, info, metrics
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always
management.endpoint.info.enabled=true
management.endpoint.health.probes.enabled=true

# Informations personnalisées pour /actuator/info
info.app.name=Candidat Microservice
info.app.description=Service de gestion des candidats et adresses
info.app.version=1.0.0